<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <!-- API -->
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="10.1.0" />
    <PackageVersion Include="Swashbuckle.AspNetCore.Swagger" Version="10.1.7" />
    <PackageVersion Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.1.7" />
    <PackageVersion Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.7" />

    <!-- InfraEstrutura -->
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.8" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.8" />
  </ItemGroup>
</Project>